### ISSUE TITLE
Problems during installation looking for help

### ISSUE THREAD

**Issue by SteveWCG1998** [joesingo/truthdiscovery#74]
There is several error during installation here. I've already follow the instruction in README

error: subprocess-exited-with-error  python setup.py egg_info did not run successfully

error:metadata-generation-failed encountered-eooro while generating package metadata

**Comment by joesingo** [comment]
Thanks for opening this issue. It looks like the dependencies in `requirements.txt` were very old. I just updated them and installation seems to be fine now.

If you can grab the latest master and try again, let me know if it works for you!

**Comment by c-steve-wang** [comment]
Thanks for your help to solve previous problems. But I still encountered another problem listed following 
ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly

**Comment by joesingo** [comment]
I'm happy to help but it's difficult to say what might be the problem without more info. Please include the full output of the `pip install` command, not just the final error message.

It would also be helpful to know what version of python/pip you are using (paste the output of `pip --version`) and which operating system you are on.

In the meantime it might be worth making sure you are using the latest version of pip (run `pip install --upgrade pip`)

**Comment by c-steve-wang** [comment]
Thank you so much for warmly help.I'm using the latest version of pip and here is the full output of the 
`Building wheels for collected packages: pycairo
  Building wheel for pycairo (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycairo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-310
      creating build/lib.macosx-10.9-universal2-cpython-310/cairo
      copying cairo/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/cairo
      copying cairo/__init__.pyi -> build/lib.macosx-10.9-universal2-cpython-310/cairo
      copying cairo/py.typed -> build/lib.macosx-10.9-universal2-cpython-310/cairo
      running build_ext
      'pkg-config' not found.
      Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycairo
Failed to build pycairo
ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects

**Comment by joesingo** [comment]
By the way, pycairo is only needed for producing PNG images of truth discovery networks (e.g. in the web interface or with the `truthdiscovery graph` command line program). If you don't need this, as a temporary workaround you could try removing the line `pycairo==1.23.0` from `requirements.txt` and installing again.

**Comment by joesingo** [comment]
Looks like you're on mac OS. The problem here is installing pycairo; looking at [their installation guide](https://pycairo.readthedocs.io/en/latest/getting_started.html), they suggest running the following:
```sh
brew install cairo pkg-config
```
For this you will need [homebrew](https://brew.sh/)

**Comment by c-steve-wang** [comment]
OK. I will try this soulution later. Thanks a lot for all your help!

**Comment by c-steve-wang** [comment]
Thanks you so much for you previous help. I have solved installation problem but still unable to run the truthdiscovery --help.
`File "/Users/chenguangwang/Desktop/base/truthdiscovery/truthdiscovery/__init__.py", line 3, in <module>
    from truthdiscovery.graphs import *
  File "/Users/chenguangwang/Desktop/base/truthdiscovery/truthdiscovery/graphs/__init__.py", line 1, in <module>
    from truthdiscovery.graphs.animation import (
  File "/Users/chenguangwang/Desktop/base/truthdiscovery/truthdiscovery/graphs/animation.py", line 6, in <module>
    from truthdiscovery.graphs.backends import JsonBackend, PngBackend
  File "/Users/chenguangwang/Desktop/base/truthdiscovery/truthdiscovery/graphs/backends/__init__.py", line 3, in <module>
    from truthdiscovery.graphs.backends.png_backend import PngBackend
  File "/Users/chenguangwang/Desktop/base/truthdiscovery/truthdiscovery/graphs/backends/png_backend.py", line 3, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
(venv) (base) chenguangwang@Chenguangs-MacBook-Pro truthdiscovery % pip install pycairo
Requirement already satisfied: pycairo in ./venv/lib/python3.10/site-packages (1.23.0)`
Above is the error inforamtion.

I only want to use the algorithms to implement on csv datasets. Would you mind to tell me about how to block the pycairo or rebuild the algorithms based on your work?

**Comment by joesingo** [comment]
It seems strange that you have the "No module named 'cairo'" error, but `pip` also says pycairo is already installed... I'm not sure exactly what's going on there. Perhaps you can paste the output of `pip freeze`? Or try deleting and recreating the virtual environment and reinstalling truthdiscovery.

If you want to just avoid importing cairo at all, as a hack you can edit `truthdiscovery/graphs/backends/png_backend.py` and replace
```python
import cairo
```
with
```python
try:
    import cairo
except ImportError:
    pass
```

Of course this will mean you won't be able to do anything involving saving graphs as PNGs, but if you're not interested in that anyway it may work for you!

**Comment by c-steve-wang** [comment]
Thank you so much for you help.After I blocked the "cairo" part. Everything workwell as I hoped. Hope you have a good day!
